### ISSUE TITLE
Feature request:  Allow the laser preview window to undock or resize further/larger

### ISSUE THREAD

**Issue by dheista** [Wickedlasers/libLaserdockCore#13]
On a retina macbook pro with a lot of screen resolution:
<img width="313" alt="Screen Shot 2022-01-01 at 9 35 40 AM" src="https://user-images.githubusercontent.com/1724371/147852931-75e3eac9-3bb3-4866-9264-4b6534cd6e8e.png">
 
The LaserOS window can be very large, but the laser preview is quite small relative to the rest of the app as shown below.
It would be ideal to allow the laser preview to undock into a separate, resizable window.  If that's not possible, at least the width of the left hand tools & preview window should be expandable further...  You can see in the attached screenshot below, the preview window is fairly small on my screen, and it's expanded as far as it can.

<img width="1952" alt="Screen Shot 2022-01-01 at 9 37 40 AM" src="https://user-images.githubusercontent.com/1724371/147852971-8a1417f8-1aea-4df6-af9c-8d998d7f11b5.png">

**Comment by gavrushkin** [comment]
@dheista thank you for notice, we'll allow to expand it further in the next version

**Comment by gavrushkin** [comment]
Done and will be included in the next release, thank you.

@dheista this issues list is for libLaserdockCore development only so use reddit/facebook/support@laseros.com next time please
