### ISSUE TITLE
Awesome to have this open-sourced! 

### ISSUE THREAD

**Issue by hegelstad** [Wickedlasers/libLaserdockCore#5]
Question:

I've been looking through the repository, but I still wonder which are the relevant files to draw "Beam"-shows, or read existing beam-show files. In addition, I am looking for the set of basic mathematical functions that can be composed into show frames.

I want to do two things:
 - Develop a show/frame builder for laser shows in JS that runs as a webapp. My idea is that it could provide a marketplace where artists can create, upload and sell their shows/frames/animations.
 - Develop another module to the webapp that uses WebUSB api to send frames to the LaserDock.

I have previously been able to send hand made custom frames to the LaserDock via WebUSB api, but this open-sourcing really will make a difference in what I can achieve with limited time in my hands.

**Comment by gavrushkin** [comment]
Hi,

What do you mean by beam-show files? 

If you mean ILD files you can use ldLzrHelper and read ILD files directly into app. You should set cmake option LD_CORE_ENABLE_LIBLZR=ON to compile library with this functionality. Then you can convert lzr points to openlase with ldLzrHelper  and draw points in ldVisualizer-inherited class with Openlase. 

All maths functions are in Helpers/Maths/ldMaths.h

**Comment by hegelstad** [comment]
I suppose you answered my question. I was thinking of the mode that displays shows suitable for shooting towards the crowd like you would expect from raves. I feel that the LaserDock is lacking in that department, even though you do have the possibility to play some beam shows, there are no ways to make your own or customize the prexisting other than through effects/filters.

**Comment by gavrushkin** [comment]
There is no ILD editing tool, you right. But you can get lzr/openlase points and modify it any way you like, e.g add other ILD files to the same visualizer, change colors in points, draw your own points. What do you want to customize exactly?
